### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by rainolf** [aniesshsethh/GoogleAutocomplete#1]
Hello,
since 2 weeks it doesn't work anymore.

No upgrades made...No possibility to debug with firebug.

Tried with bith Firefox and Chrome.

Does anything is changed on Google side? Is it any solution?

Thank you

**Comment by aniesshsethh** [comment]
Hi Rainolf, 

I will have a look at it tonight and will get back to you. 

Thanks

Best Regards

Aniessh Sethh

**Comment by rainolf** [comment]
Appreciate....if you need further info i'm here

Thank you

2015-12-17 10:17 GMT+01:00 Aniessh Sethh notifications@github.com:

**Comment by Sid6555** [comment]
Any update on this issue.

**Comment by aniesshsethh** [comment]
Sorry, weather took me down, here is a fix.

**Comment by rainolf** [comment]
Thank you.

I will try and let you know

2015-12-19 11:27 GMT+01:00 Aniessh Sethh notifications@github.com:

**Comment by Sid6555** [comment]
Good job. Keep it up. Please close the issue.
