### ISSUE TITLE
Change formatting in Output

### ISSUE THREAD

**Issue by TTmiro** [aniesshsethh/GoogleAutocomplete#2]
Hi Aniessh,

first of all: I really appreciate you effort in writing this add-on. I'm using it in SuiteCRM (latest version). On the left hand side of the screenshot you can see how the result is now and on the right hand side how I would like it to be. Can you support me in this case?

Thanks in advance,
Michel

![2016-09-01](https://cloud.githubusercontent.com/assets/20082816/18158916/7a5c7abc-7026-11e6-8dff-16f7be69913f.PNG)

**Comment by aniesshsethh** [comment]
Hi Michel, 

Sure I will help you with that, it's just that I am a bit busy till next Wednesday, would be able to get on this after that. 

Please let me know. 

Thanks

Best Regards

Aniessh Sethh

**Comment by TTmiro** [comment]
Hi Aniessh,

fine with me. Thank you for your support!

Best,
Michel

**Comment by aniesshsethh** [comment]
I am sorry for the delay Michel, here you go https://github.com/aniesshsethh/GoogleAutocomplete/pull/4/files, would you be able to merge it in ?

**Comment by aniesshsethh** [comment]
Closing the issue due to lack of response from @TTmiro
